name: Generate Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Generate snake game
      uses: Platane/snk@v3
      with:
        github_user_name: ayushshanks

    # Upload artifacts for download if needed
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: snake-outputs
        path: dist/
    
    # Optional: Commit and push the generated snake files to the repository
    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Action"
        git add dist/
        git commit -m "Add generated snake SVG and GIF"
        git push
